### ISSUE TITLE
Add Support for AMD modules and bower

### ISSUE THREAD

**Issue by benmccormick** [behave-ui/behave-ui-hotkeys#2]
Hey @kkemple, great work on this behavior.  It's exactly what I was hoping to find when I started looking for a keyboard shortcut library this evening.

Would you be willing to accept a pull request that made this lib available through bower and was wrapped as a UMD module rather than plain commonjs so that it could be used by those of us not using browserify?

I'm happy to do the work so I can use it, but wanted to ask/discuss because it effects the build process/directory & what's checked into the repository, its not just a quick code change.

Generally my thought would be that for a small library like this it's easiest to just pull it all into one file if you're making it UMD format, since otherwise you'll have to do a build step and still check in the final product (so its available in UMD within the repo).  Since you haven't gone that direction so far, I wanted to ask what your thoughts were first.

**Comment by kkemple** [comment]
I am completely open to it! I just started to really embrace the idea of making a real library of behaviors/helpers for marionette apps and I want to be usable everywhere.

I planned to move this to a UMD style module by v0.1.0 so by all means go for it man!
